# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('e164', models.CharField(db_index=True, max_length=255, unique=True)),
                ('opt_in', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('queued', models.DateTimeField(blank=True, default=None, null=True)),
                ('processed', models.DateTimeField(blank=True, default=None, null=True)),
                ('content', models.TextField(blank=True, default='')),
                ('media_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('from_ep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_message_set', to='twilio.EndPoint')),
                ('to_ep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_message_set', to='twilio.EndPoint')),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('value', models.TextField(blank=True, default='')),
            ],
        ),
    ]
