# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('twilio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioMessage',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('processed', models.DateTimeField(blank=True, default=None, null=True)),
                ('to_country', models.TextField(blank=True, default='')),
                ('to_state', models.TextField(blank=True, default='')),
                ('sms_message_sid', models.TextField(blank=True, default='')),
                ('num_media', models.IntegerField(default=None, null=True)),
                ('to_city', models.TextField(blank=True, default='')),
                ('from_zip', models.TextField(blank=True, default='')),
                ('sms_sid', models.TextField(blank=True, default='')),
                ('from_state', models.TextField(blank=True, default='')),
                ('sms_status', models.TextField(blank=True, default='')),
                ('from_city', models.TextField(blank=True, default='')),
                ('to_e164', models.TextField(blank=True, default='')),
                ('messaging_service_sid', models.TextField(blank=True, default='')),
                ('to_zip', models.TextField(blank=True, default='')),
                ('num_segments', models.IntegerField(default=None, null=True)),
                ('message_sid', models.TextField(blank=True, default='')),
                ('account_sid', models.TextField(blank=True, default='')),
                ('from_e164', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('api_version', models.DateField(default=None, null=True)),
            ],
        ),
    ]
