# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, default="{% extends 'www/base.html' %}\n\n{% block content %}\n  Add some content.\n{% endblock %}\n"),
        ),
        migrations.AlterField(
            model_name='page',
            name='position',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
