# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import www.models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20160502_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('number', models.CharField(db_index=True, default=www.models.gen_ticket_id, max_length=16, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('closed', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, default="{% extends 'www/base.html' %}\n\n{% block head %}\n{% endblock %}\n\n{% block content %}\n  Add some content.\n{% endblock %}\n"),
        ),
    ]
